name: REUSE Compliance

on: [push, pull_request]

jobs:
  reuse:
    runs-on: [ self-hosted, linux, x64 ]
    timeout-minutes: 15
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run reuse lint
        uses: fsfe/reuse-action@v3

