name: Yamllint

on: [push, pull_request]

jobs:
  yamllint:
    runs-on: [ self-hosted, linux, x64 ]
    timeout-minutes: 15
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install yamllint
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install yamllint

      - name: Run yamllint
        uses: ibiqlik/action-yamllint@v3

